//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemphisHospital.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Required]
        public int ID { get; set; }
        [Required(ErrorMessage ="Enter a username")]
        [Display(Name = "Enter a username")]
        public string UserName { get; set; }
        [Required(ErrorMessage ="Enter a password")]
        [Display(Name ="Enter a password")]
        public string Password { get; set; }
    }
}
